import { Download, FileText } from "lucide-react";
import { useMemo, useState } from "react";
import { core, coreUrl } from "../core-api/client";
import type { CoreRegionState, CoreState, CoreStateDistrictRow } from "../core-api/types";
import { LevelDot, Load, OfficialAlert, Provenance, Section } from "../components/ui";
import { istDateTime, num, signed } from "../lib/format";
import { LEVEL } from "../lib/present";
import { useApp } from "../lib/store";
import { useCore } from "../lib/useCore";

type Col = { key: keyof CoreStateDistrictRow | "level"; label: string; get: (r: CoreStateDistrictRow) => number | null; fmt: (r: CoreStateDistrictRow) => string };

const RISK_COLS: Col[] = [
  { key: "level", label: "Highest level", get: (r) => r.max_level, fmt: (r) => LEVEL[r.max_level]?.name ?? "—" },
  { key: "tmax_7d_max", label: "Max °C (7 d)", get: (r) => r.tmax_7d_max, fmt: (r) => num(r.tmax_7d_max, 1) },
  { key: "tmin_7d_min", label: "Min °C (7 d)", get: (r) => r.tmin_7d_min, fmt: (r) => num(r.tmin_7d_min, 1) },
  { key: "rain_7d", label: "Rain mm (7 d)", get: (r) => r.rain_7d, fmt: (r) => num(r.rain_7d, 1) },
  { key: "gust_max", label: "Max gust km/h", get: (r) => r.gust_max, fmt: (r) => num(r.gust_max) },
  { key: "official_warnings", label: "Official alerts", get: (r) => r.official_warnings, fmt: (r) => String(r.official_warnings) },
];
const NORMAL_COLS: Col[] = [
  { key: "tmax_anom_7d", label: "Max temp vs normal (7 d)", get: (r) => r.tmax_anom_7d, fmt: (r) => `${signed(r.tmax_anom_7d)} °C` },
  { key: "rain_7d", label: "Rain 7 d / normal", get: (r) => r.rain_7d, fmt: (r) => `${num(r.rain_7d, 1)} / ${num(r.rain_7d_normal, 1)}` },
  { key: "rain_30d_pct", label: "Past 30 d rain vs normal", get: (r) => r.rain_30d_pct, fmt: (r) => `${signed(r.rain_30d_pct, 0)}%` },
  { key: "rain_30d_cat", label: "Category (IMD)", get: (r) => r.rain_30d_pct, fmt: (r) => r.rain_30d_cat ?? "—" },
];

/** State drill-down from CORE /region/state (existing district table, alerts and exports). */
export default function GovernmentStateTable({ title, focus = "risk" }: { title: string; focus?: "risk" | "normal" }) {
  const { govState, setGovState, place } = useApp();
  const states = useCore<CoreState[]>("states", core.states);
  const slug = govState ?? (states.state === "ok" ? states.data.find((s) => s.state === place.state)?.state_slug ?? null : null);
  const data = useCore<CoreRegionState>(slug ? `state:${slug}` : null, () => core.regionState(slug!));
  const cols = focus === "risk" ? RISK_COLS : NORMAL_COLS;
  const [sort, setSort] = useState<{ i: number; desc: boolean }>({ i: 0, desc: true });

  return (
    <div className="space-y-6" data-testid="gov-state">
      <Section title={title}>
        <div className="flex flex-wrap items-center gap-2 text-[13px]">
          <select value={slug ?? ""} onChange={(e) => setGovState(e.target.value || null)} className="h-9 rounded-lg border border-line bg-surface px-2" aria-label="State">
            <option value="">Select state or UT</option>
            {states.state === "ok" && states.data.map((s) => <option key={s.state_slug} value={s.state_slug}>{s.state}</option>)}
          </select>
          {slug && (
            <>
              <a href={coreUrl(`/region/state/${slug}/export.xlsx`)} className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-line px-2.5 hover:border-accent"><Download size={14} /> Excel</a>
              <a href={coreUrl(`/region/state/${slug}/report.html`)} target="_blank" rel="noreferrer" className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-line px-2.5 hover:border-accent"><FileText size={14} /> Printable briefing</a>
              <span className="text-[11.5px] text-muted">Exports are generated by CORE.</span>
            </>
          )}
        </div>
      </Section>
      {!slug && <p className="text-[13.5px] text-muted">Choose a state to see its district table.</p>}
      {slug && (
        <Load s={data} lines={10}>
          {(d) => <Table d={d} cols={cols} sort={sort} setSort={setSort} />}
        </Load>
      )}
      {slug && data.state === "loading" && <p className="text-[12px] text-muted">CORE computes the state table from each district's forecast; the first request can take up to a minute.</p>}
    </div>
  );
}

function Table({ d, cols, sort, setSort }: { d: CoreRegionState; cols: Col[]; sort: { i: number; desc: boolean }; setSort: (s: { i: number; desc: boolean }) => void }) {
  const rows = useMemo(() => [...d.districts].sort((a, b) => {
    const x = cols[sort.i].get(a) ?? -Infinity, y = cols[sort.i].get(b) ?? -Infinity;
    return sort.desc ? (y as number) - (x as number) : (x as number) - (y as number);
  }), [d, cols, sort]);
  return (
    <div className="space-y-5">
      <div className="overflow-x-auto">
        <table className="w-full min-w-[640px] text-[12.5px] tabular-nums" data-testid="state-table">
          <thead className="text-left text-muted"><tr className="border-b border-line">
            <th className="py-1.5 font-normal">District</th>
            {cols.map((c, i) => (
              <th key={c.label} className="text-right font-normal">
                <button onClick={() => setSort({ i, desc: sort.i === i ? !sort.desc : true })} className="hover:text-text">{c.label}{sort.i === i ? (sort.desc ? " ↓" : " ↑") : ""}</button>
              </th>
            ))}
          </tr></thead>
          <tbody>{rows.map((r) => (
            <tr key={r.id} className="border-b border-line/60" data-district={r.id}>
              <td className="py-1.5"><span className="inline-flex items-center gap-2"><LevelDot level={r.max_level} />{r.district}</span> <span className="text-[11px] text-muted">{r.terrain}</span></td>
              {cols.map((c) => <td key={c.label} className="text-right">{c.fmt(r)}</td>)}
            </tr>
          ))}</tbody>
        </table>
      </div>
      <p className="text-[11.5px] leading-relaxed text-muted">{d.method} Levels are CORE's existing risk rules (system assessments, not official warnings). Generated {istDateTime(d.generated_at)}.</p>
      {d.warnings.length > 0 && (
        <Section title={`Official alerts — ${d.state}`}><div className="grid gap-2 lg:grid-cols-2">{d.warnings.map((w) => <OfficialAlert key={w.id} w={w} />)}</div></Section>
      )}
      {d.notices.map((n) => <p key={n} className="text-[12px] text-amber-200">{n}</p>)}
      <Provenance sources={d.sources} />
    </div>
  );
}
